### ISSUE TITLE
Collated Bug Reports: Things to do

### ISSUE THREAD

**Issue by garyheng** [CS2113-AY1819S1-T13-5/main#200]
## General bugs

- [x] #179 : Unable to add a new workout despite the name of the workout is different.
- [x] #181 : Editing same parameter twice bug
- [x] #186 : Valid execution for invalid list command
- [x] #188 : Adding command error
- [x] #196 : Find command suppose to find keywords not characters within name of workout
- [x] #197 : Warning never show (@DarylTew @sijieg)

## General recommendations

- [x] #183 : Error message for editing nothing
- [x] #187 : Duration can only integers
- [x] #192 : Can improve the content format in result box

### Traversing : @yicheng12  

- [x] #191 : Cannot filter by only one prefix
- [x] #193 : More flexible find or filter command (Recommendation)

### Modify : @sijieg 

- [x] #180 : Modifying user profile with modify command does not change user profile
- [x] #182 : Modify accepts empty argument
- [x] #195 : Invalid user gender

### Track : @garyheng 

- [x] #189 : Tracking issue for muscle groups is not working

### Recommend: @shouteck 

- [x] #194 : Recommend accepting gibberish inputs
- [x] #198 : Different things recommended each time
- [x] #199 : Recommend works without any parameters.

### Current: @DarylTew 

- [x] #184 : Unable to start a new workout despite deleting the workout that i started
- [x] #185 : Documentation bug for summary of commands
- [x] #190 : Deleted item still under track

**Comment by sijieg** [comment]
#204 PR fixes #197 #180 #182 #195

**Comment by sijieg** [comment]
Close #187 Duration should only take in integers, as stated in the user guide.

**Comment by sijieg** [comment]
Close #179 and #188 (both are about adding duplicate workouts)
Update UserGuide for add command
Duplicate workouts will include same name, different name but every other parameter is exactly the same.

**Comment by shouteck** [comment]
Close #199 and #198 
User guide has explicitly stated that recommend command will recommend a workout and that recommend will work without parameters where a workout will be recommended using the workout presets in the user profile.

**Comment by garyheng** [comment]
PR #213 
- Fix for bug in issue #189 
- Closing issue #170

**Comment by garyheng** [comment]
PR #253 fixes issus #196

**Comment by garyheng** [comment]
All bug reports settled, closing issue.
